#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

echo ""
echo " GOCARBON_VERSION: ${GOCARBON_VERSION}"
echo " BUILD_DATE      : ${BUILD_DATE}"
echo " GIT_SHA1        : ${GIT_SHA1}"
echo ""

docker build \
  --file Dockerfile \
  --rm \
  --compress \
  --build-arg VCS_REF=${GIT_SHA1} \
  --build-arg BUILD_DATE=${BUILD_DATE} \
  --build-arg BUILD_VERSION=${BUILD_VERSION} \
  --build-arg BUILD_TYPE=${BUILD_TYPE} \
  --build-arg GOCARBON_VERSION=${GOCARBON_VERSION} \
  --tag ${DOCKER_NAME_SPACE}/${DOCKER_IMAGE_NAME}:${DOCKER_VERSION} .
